tasks:
  - name: Open the readme, contract and test
    command: gp open contracts/Token.sol && gp open test/Token.js && gp open README.md
  
  - name: Hardhat server
    init: npm install
    command: npx hardhat node

  - name: Frontend server
    command: npx hardhat --network localhost run scripts/deploy.js && cd frontend && npm install && npm run start
    openMode: split-right
